# -*- coding: utf-8 -*-
"""revisioneCovariance And Correlation with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ES8LjXA5XXSabNUJtrSUEY9IaMENHtd

#Covariance And Correlation with Python
"""

import seaborn as sns

df =sns.load_dataset("healthexp")

df.head()

df.tail()

## covariance
df.select_dtypes(include=['number']).cov()

## person correlation and coefficient
df.select_dtypes(include=['number']).corr(method='pearson')

## spearman rank correlation
df.select_dtypes(include=["number"]).corr(method="spearman")

"""# let's load new dataset

"""

df1=sns.load_dataset("tips")

df1.head()

## covariance
df.select_dtypes(include=["number"]).cov()

## pearson correlation coefficient
df.select_dtypes(include=["number"]).corr(method="pearson")

#spearman rank correlation
df.select_dtypes(include=["number"]).corr(method="spearman")

## one more dataset
df2 = sns.load_dataset("mpg")

df2.head()

## covariance
df2.select_dtypes(include=["number"]).cov()

## pearson coefficiant correlation
df2.select_dtypes(include=["number"]).corr(method="pearson")

## spearman rank correlation
df2.select_dtypes(include=["number"]).corr(method="spearman")

