# -*- coding: utf-8 -*-
"""revision Target Guided Ordinal Encoding .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m3AzyThBVsggpKsJA3JI9Ko114b0je2T

# Target Guided Ordinal encoding
~ here we find relationship b/w independent feature and dependent feature(targetfeature)
"""

#create sample dataframe with a categorical variable and a target variable
import pandas as pd

df=pd.DataFrame({
    'city':['new york','london','paris','tokyo','new york','paris'],
    'price':[200,150,300,250,150,320]
})

df

## calculate the mean price for each city

df.groupby('city')['price'].mean()

## new convert in dict form
mean_price=df.groupby('city')['price'].mean().to_dict()
mean_price

##replace each city with it's mean price
df["encoded_city"]=df['city'].map(mean_price)

df["encoded_city"]

## now check df
df

"""# Let's try in  tips dataset

"""

import seaborn as sns

df= sns.load_dataset('tips')

df

## here, I want to know how many people spend money in food  which time and day ,
# here target feature is totall_bill

#calculate mean price of totall_bill for each sex and day
mean_price=df.groupby(['sex','day'])['total_bill'].mean().to_dict()
mean_price

# replace with each sex and day  with mean_price
df['encoded_sex_day']=df[['sex','day']].apply(lambda x: mean_price[(x['sex'],x['day'])],axis=1)

df["encoded_sex_day"]

df

## how  many female spend money on food on sunday

# Filter for females
female_df = df[df['sex'] == 'Female']

# Filter for Sundays
sunday_df = female_df[female_df['day'] == 'Sun']

# Count the number of females who spent money on food on Sunday
num_women_sunday = len(sunday_df)

print(f"The number of women who spent money on food on Sunday is: {num_women_sunday}")

# how may male spend mony on food on Sat
men_df = df[df["sex"]=="Male"]
sat_df = men_df[men_df["day"]=="Sat"]
num_men_sat = len(sat_df)
print(f"The number of men who spent money on food on Saturday is: {num_men_sat}")

